### ISSUE TITLE
Warnings and weird things before connecting

### ISSUE THREAD

**Issue by jpink** [boc-tothefuture/kotlin-homieiot#2]
Hi,

I have three questions of things:

## Question 1: Defining device

When you create `Device` and add nodes, properties and subscriptions to them you get lot of warnings before connecting: 

> WARN org.homieiot.mqtt.RootHomiePublisher - Message (true) published on topic (foo/bar/baz/$settable) without connected MqttClient
WARN org.homieiot.mqtt.RootHomiePublisher - Message (baz,bax) published on topic (foo/bar/$properties) without connected MqttClient
WARN org.homieiot.mqtt.RootHomiePublisher - Message (bai,bar) published on topic (foo/$nodes) without connected MqttClient

## Question 2: Publishing topics multiple times

Second noticeable thing is that nodes and properties are published one by one (incrementally) e.g. `homie/foo/$nodes → "bar"` and then `homie/foo/$nodes → "bar,baz"`.

Do you have any plans avoid these warnings and incomplete array values? All topics should be sent during ½ s from connecting, see [Timings](https://homieiot.github.io/specification/#timings). I think there should be 3 phases after connecting:

1. (Define and) publish all topics once.
2. Publish device state (to ready or alert).
3. Other topic value updates etc.

## Question 3: Best connecting practice

When I connect in main method like `client.connect().get()` the main thread will continue quite fast to the  end of program or `System.exit(0)`. How to wait (forever) and not consuming CPU cycles.

## /homie/off/topic

These aren't real problems, just wondering. This repository is young and very good. *Thanks!*

**Comment by boc-tothefuture** [comment]
WOAH!!! @jpink I apologize I never saw this issue opened and it is has been open a long time.  I missed the notification somehow. 

You are correct on issue #1.  I will open that open that up to be resolved.  I need to think about how to handle it within the code.  

I think #2 is really related to #1.  Because you get those warnings as the structure is being built up.  But the actual publication happens the connect call.  

on #3 - it will probably be application dependant.  For example if you are using this to poll data from another system and publish it over the homie protocol I would expect that polling to be driving the application flow.  Do you think the library should have a non returning version of connect?  I would need to think about that and would be interested in your use case!

**Comment by boc-tothefuture** [comment]
Closed based on #4
